replicaCount: 1

image:
  repository: cloudcrafter/users
  tag: "v1.0.0"
  pullPolicy: Never

service:
  type: ClusterIP
  port: 3001

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "200m"
    memory: "128Mi"